### ISSUE TITLE
Promtail failed to tail file

### ISSUE THREAD

**Issue by anjeludo** [thbrunzendorf/monitoring-demo#1]
Hi,

I get this error after running docker-compose up :

monitoring-promtail | level=error ts=2021-01-10T22:55:24.046511109Z caller=filetarget.go:299 msg="failed to tail file" error="file is a directory" filename=/var/log/monitoring.log

¿Any idea?

Thank you.

**Comment by anjeludo** [comment]
Sorry. My mistake :)

**Comment by thbrunzendorf** [comment]
No worries :)
